### ISSUE TITLE
Git clone depth 1

### ISSUE THREAD

**Issue by DaveSenn** [jakubgarfield/Bonobo-Git-Server#166]
I'd like to clone a very "minimalistic" version of my repo.
I tried this using the following command:
```bash
git clone http://gitServer/Repo.git --branch Branch1 --single-branch --depth 1 Branch1
```
The command never finishes.
When I start the same command (without using Bonobo) it works:
```bash
git clone "C:\PathToRepo\Repo" "C:\Dest\Repo" --branch Branch1 --single-branch --depth 1
```
Am i doing something wrong or has Bonobo a problem with --depth 1?

**Comment by joeljeske** [comment]
Depth --1 [is automatically added][0] by bower v>=1.4.0 due to feature detection done [here][1]. Bonobo is saying it support shallowing cloning but then hangs when requested to do so. Please get this fixed as we cannot use the latest bower version with bonobo.

[0]: https://github.com/bower/bower/blob/master/lib/core/resolvers/GitRemoteResolver.js#L123
[1]: https://github.com/bower/bower/pull/1628/files#diff-4d9db09214cdd3741142579dc6c224c5R168

**Comment by RedX2501** [comment]
Is this still an issue with 5.1.1?
if it is please reopen the issue.
