### ISSUE TITLE
Add button to create files + How to use Bonobo

### ISSUE THREAD

**Issue by StEvUgnIn** [jakubgarfield/Bonobo-Git-Server#169]
Hi,
I installed Bonobo.Git Server for my teacher and I noticed there's no '+' button like in Git Hub. I find this too bad, this functionality really misses and we didn't understand how to upload files on the server.

I was planning to look for the place of the files and add them manually instead of copy or anything else.

What is the best option for us ? We don't use Git clients and my teacher is not familiarised with git command line tool.

Thank you.

**Comment by StEvUgnIn** [comment]
OK...
But can I push my project on the server. I don't understand. I tried on this morning with Git Hub client, but impossible to log in with my Bonobo.Git account as Git Hub Enterprise.

**Comment by StEvUgnIn** [comment]
Sorry for this late answer. I'm very busy these days.

What I don't understand is uploading. How am I sensed to upload my repositery/project on the server.
I would prefer to use some IDE and then create a project on the server and edit the files : When I'm done,  I would like to upload.

In what way does Bonobo get used ?

**Comment by jafp** [comment]
@StEvUgnIn: I think many of your questions can be answered by reading the "official" tutorial on the Git website: http://git-scm.com/docs/gittutorial

**Comment by Cherrg** [comment]
Hi there, i know this is an old question, but it costs nothing to ask :)
 
jakubgarfield:
> The edit file functionality is out of scope for this project

Maybe i found 2 usable approaches to implement this feature with (hopefully) less work to do:

1. Someone implemented this feature in java to show how it can be done (https://github.com/junoyoon/git-online-commit-sample). 
There are 6 small classes you could possibly port to c#. (The project uses jgit library. There is a c# port https://github.com/mono/ngit)

2. First use normal file upload for IIS (https://docs.microsoft.com/en-us/aspnet/web-forms/overview/data-access/working-with-binary-files/uploading-files-cs)
and use somethin like this: http://stackoverflow.com/questions/9670302/commit-directly-to-a-bare-repository
(instead of blob you can use a git hash-object to simplyfy the code...)

Unfurtunatly i never programmed something in c# and for IIS Server so i don't know where to begin with to test/implement it myself...

**Comment by StEvUgnIn** [comment]
I gave up and I left the server in the same state.

I don't manage servers these days.  

Thank you for clues.
