### ISSUE TITLE
Error when cloning a repository

### ISSUE THREAD

**Issue by iamvitali** [jakubgarfield/Bonobo-Git-Server#283]
Hi,
I'm running the Bonobo Git Server on 8.5 IIS with a Windows authentication (so I have a "git" and "git.windows" folder).
Everything seems to be working, and I can create repositories easily but if I want to click the "Clone" button on the website on a repository that I've already created (doesn't matter if it has any commits/files or not, tried both) I get this error: "An error occurred when processing your request. Please try again or contact the system administrator.". So I can create repositories but not make duplicates of them for some reason.

**Comment by KY4U** [comment]
Hello,

I was able to track down this issue.  After looking at the code it was determined that logo BinaryData and logo RemoveLogo information is not being set properly in the RepositoryDetailModel parameter sent to the ConvertRepositoryDetailModel function in RepositoryController.cs (line 558)

As a temporary fix I changed the following lines from:
569                AuditPushUser = model.AuditPushUser,
570                Logo = model.Logo.BinaryData,
571                RemoveLogo = model.Logo.RemoveLogo

to:
569                AuditPushUser = model.AuditPushUser
570                // Logo = model.Logo.BinaryData,
571                // RemoveLogo = model.Logo.RemoveLogo

I hope this information will help the developers correct the issue for a future release.  In the mean time I'll try to determine where the model needs updating so that the logo information gets put in there properly.

**Comment by jakubgarfield** [comment]
@SanSYS: do you have any idea what might be causing the issue?

**Comment by svermeulen** [comment]
Thanks KY4U, your workaround helped me

**Comment by iamvitali** [comment]
@KY4U Thanks for the possible solution.
I've searched the folder and there is no file named RepositoryController.cs. Based on this github it's in the Controllers folder which is nowhere to be found on my server, I assume it's all source code and for the fix to work I would need to somehow compile it?

Thanks.

**Comment by latop2604** [comment]
@iamvitali You need to recompile the source code.

**Comment by Jsshhua** [comment]
Hi guys, can you please help me to fix my problem. I have some issue with cloning repository. It says"
"fatal: unable to access 'https://@git.eu-gb.bluemix.net:tectonic/app-escalateai.git/': Port number ended with 't'" thanks in advance.
