### ISSUE TITLE
Add Custom Port to Settings

### ISSUE THREAD

**Issue by dbeals** [jakubgarfield/Bonobo-Git-Server#294]
My Git server is routed through a different port number (from my router), so the URLs listed are not completely accurate. It would be great to be able to enter in a custom port number in the settings and have our URL reflect that.

**Comment by kiddailey** [comment]
Can you be more specific?  I use Bonobo on a server with custom ports and everything works as expected (from what I can tell).

FWIW, if you're behind a NAT translation in your router/firewall and the incoming ports on the router aren't the same as the ports on the server, you will have an issue with mismatched ports.

**Comment by dbeals** [comment]
I apologize, I should have included an example with my initial post; that is what I meant. The server uses the standard port, but when accessing the server from an external URL my router is expecting a different port. As such, the site displays that the URL is http://myserverurl.com/MyRepository.git rather than http://myserverurl.com:####/MyRepository.git.

**Comment by kiddailey** [comment]
That's what I assumed you meant.  As I mentioned, this is probably because the port your server is listening on (seemingly 80 in your example) does not match your router (#### in your example).

Bonobo picks up the port from the server it's running on.  In order to get them to match, you need to bind the Bonobo server/site to the same port and adjust the NAT on your router to route to the server also on the same port.

I have this same setup in my environment and it works as expected.

**Comment by dbeals** [comment]
Not sure why I didn't think about rebinding through IIS. I changed my port on the server and it is working properly now. Thanks!
