### ISSUE TITLE
Issue getting Windows Authentication working

### ISSUE THREAD

**Issue by spongessuck** [jakubgarfield/Bonobo-Git-Server#333]
I'm trying to install Bonobo 5.0.0 on Windows 7 + IIS 7.5 with Windows authentication.

When I go to the homepage (`http://domain/bonobo`), I'm prompted for my Windows username/password and after that it redirects back to the root to look for a route called windowsAuthCallback:

    http://domain/windowsAuthCallback?id=xxx

Obviously this gives me a 404 error.

I have authentication set to 'anonymous' in IIS and 'Windows' in the Bonobo web.config and I'm not sure what I'm doing wrong.

Not sure if this is related... I have an existing Bonobo installation on the same server and I'm installing Bonobo 5 fresh as a new application. After running into the issue I described, trying to open the original Bonobo app gives me the following error:

    Unable to find an entry point named 'sqlite3_open_interop' in DLL 'SQLite.Interop.dll'.

Restarting IIS resolves the issue and I can access my old Bonobo app again.

**Comment by jakubgarfield** [comment]
@ollienator, any ideas?

**Comment by larshg** [comment]
I experience the same using windows authentication and AD membership service - I have tried to localize the error, but its out of my league atm :(

Got any ideas @ollienator?

**Comment by losiu900** [comment]
I have the same problem as spongessuck.

**Comment by mirogta** [comment]
@ollienator:
It seems that version 5 is not backwards compatible with version 4.

May I suggest adding unit and/or integration tests first, before future refactoring of any code that works?

I've narrowed it down to line 30 in AuthenticationProvider.cs:
UserModel user = MembershipService.GetUser(username.StripDomain());

I have been using version 4 with Windows Authentication for some time and usernames were stored with a domain. Since in the new version the domain is removed, my valid username+password combination won't match.

I've tried to remove the .StripDomain() from the implementation and now can authenticate with AD membership service successfully.

**Comment by mirogta** [comment]
I was able to resolve this issue by editing the ~App_Data\Bonobo.Git.Server.db file, using http://sqlitebrowser.org/

I've removed the "<domain>\" prefix from my user's usernames, saved the file, and now AD authentication works fine - using AuthenticationProvider=Windows and MembershipService=Internal

Hope this helps.
