### ISSUE TITLE
Cannot build: SQLite.Interop.dll not found

### ISSUE THREAD

**Issue by damianpiccolo** [jakubgarfield/Bonobo-Git-Server#346]
I tried downloading the compiled server but it's not working since it doesn't let me login with admin/admin.
I downloaded all the code with the hope of debugging that issue, but I cannot even compile it. I'm getting the following error:
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(4105,5): error MSB3030: Could not copy the file "C:\Users\damian\Source\Repos\Bonobo-Git-Server\Bonobo.Git.Server\bin\x64\SQLite.Interop.dll" because it was not found.
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(4105,5): error MSB3030: Could not copy the file "C:\Users\damian\Source\Repos\Bonobo-Git-Server\Bonobo.Git.Server\bin\x86\SQLite.Interop.dll" because it was not found.

Pardon my ignorance

**Comment by larshg** [comment]
You can copy the files from Bonobo-Git-Server\packages\System.Data.SQLite.Core.1.0.98.1\build\net45 (copy both x86 and x64 unless you know your server enviroment architecture) to the bin folder of the project.

For some reason, even if you add the files from the above mentioned folder, VS copies them to the bin folder and add the map path from the bin folder to the project... At least for now :)

**Comment by VanKrock** [comment]
Or you can replace "PreserveNewest" to "CopyAlways" at 526 and 529 line in Bonobo.Git.Server.csproj

**Comment by damianpiccolo** [comment]
VanKrock's comment did it. Thanks!

**Comment by damianpiccolo** [comment]
I'm not sure if I should close the issue since I don't have it anymore or wait until the fix is pusshed to the project.

**Comment by j-mccombs** [comment]
I've been trying to get started testing with this project for the past few days; between this and #335 being present in the current install it made the experience less than smooth. Great experience with the product since I worked these two issues out. Would probably be useful to publish a revision to the compiled project download on the main site, and this issue occurred for me on two separate computers, so likely worth leaving open unless the issue is with SQLite?

**Comment by padremortius** [comment]
Implemented to copy libraries from the folder with the nuget-packages #353
