### ISSUE TITLE
Difference between test and real world

### ISSUE THREAD

**Issue by RedX2501** [jakubgarfield/Bonobo-Git-Server#484]
I have created a new branch `clonetests` where I test that anonymous clone works.

The problem that i'm facing is that when running IIS by myself the anonymous clone fails as it is supposed to but in the test it succeeds...

Unfortunately i have no idea on how to debug the copied version of the binaries that SpecsFor uses.

Can anyone have a look into this and confirm that it is also happening on their machine? Thank you.

**Comment by willdean** [comment]
I'll try it now.

**Comment by willdean** [comment]
It's a working directory problem in MsysgitIntegrationTests - all those relative paths are pointing to somewhere wrong.  

I'm going to assert them all valid in the initialiser for MsysgitIntegrationTests, and then work out where they go awry.  It might be safer to resolve them from relative to absolute at some point in the run where we can be confident about the working directory.

**Comment by willdean** [comment]
I've committed a fix for this - you'll see it's been committed with stupid credentials, BECAUSE THE F****ING TESTS CHANGED MY GLOBAL GIT SETUP

We absolutely must not do that.  I don't know what games need to be played with .gitconfig files or with command line arguments, but we really cannot have the test setup messing with people's real git config.

**Comment by willdean** [comment]
I've realised RunGitTests is still failing, and it wasn't clear on AppVeyor why it was - so I've added some console trace before/after a Git call so that we can see exactly what's happening.  Hopefully it will now be clearer.

Anyway, it's failing with an auth error:

> 
About to run 'N:\will\Bonobo-Git-Server\Gits\2.6.1\bin\git.exe' with args 'clone http://admin:admin@localhost:20000/Integration.git' in 'N:\will\Bonobo-Git-Server\Tests\IntegrationTests'
Output: 
Errors: Cloning into 'Integration'...
fatal: Authentication failed for 'http://admin:admin@localhost:20000/Integration.git/'

**Comment by willdean** [comment]
OK, well, under appveyor we get a different problem, which that the test is looking for "Cloning into Integration" on stdout, but Git has apparently returned "Cloning into 'Integration'...
warning: You appear to have cloned an empty repository." onto stderr.

But that looks fixable.

**Comment by willdean** [comment]
We're also going to have problems in the future with the code which runs Git and captures  Stdout/Stderr.  The accepted answer here shows how to do this robustly:

http://stackoverflow.com/questions/139593/processstartinfo-hanging-on-waitforexit-why

**Comment by RedX2501** [comment]
The RunGitTests need to create repository local credentials for the cloned test repo rule the tests will fail on AppVeyor because there are no credentials set there.

Maybe during your testing I'll guess it gut run outside your test repo and that's why it changed your credentials.

**Comment by RedX2501** [comment]
There should be no difference if both are running version 2.6.1....

**Comment by RedX2501** [comment]
Yeah i see that you fixed rungit by providing working directory to it in createcredentials that's why it changed your global settings. Working directory is not inside your cloned repo.

**Comment by RedX2501** [comment]
I pulled your changes but I'm still able to do an anonymous clone in my test on my machine... The test succeeded on your computer?

**Comment by RedX2501** [comment]
Yeah! Finally found out what was wrong!
I use the wincred helper under windows and it stores all the login information. At some point it time it stored the credentials for my login to the test url.
But i also use cygwin on the system which uses another credential store which did not have the credentials cached. This meant that there the anonymous clone was truly anonymous and thus did what i expected...

**Comment by willdean** [comment]
Can we create a local .gitconfig in the test directory which disables credential stores?  Or override it on the git command line or something?

**Comment by RedX2501** [comment]
It's what I have done in the test for the `credential.http://localhost:20000/.helper`.

https://github.com/jakubgarfield/Bonobo-Git-Server/commit/597a7a17332c5e930fd96d34eba784254ef1f5a2 Line 127

**Comment by willdean** [comment]
Right, I get you now - and the CreateIdentity stuff was **supposed** to be in the repo directory, so that was my mistake moving it to WorkingDirectory.  The AnonClone test was failing on CreateIdentity because the repo directory didn't exist before the clone was run.
