### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by RedX2501** [jakubgarfield/Bonobo-Git-Server#497]
I'd like that we set a date for the next release or an amount of improvements we want to achieve. 

I also propose that we set the next number at 6.0.0 because we have changed the database and that makes it not backwards compatible. 

I'd like to make the following changes for the new release

- [x] Move the linkify option from global to per repo.
- [x] Move the push option for anonymous repo from global to per repo.
- [x] export the users group as an environment var as requested in #495.
- [x] Support push-to-create #376

Please add to this list so we can see how long we will need for the next release .

**Comment by willdean** [comment]
I added #376, because I've already done it once, but I bottled-out because of concern about the permissions stuff, which I think is now sorted so I can rework this.

We should probably file issues for each outstanding thing and tag them 'For 6.0.0' or something, so that we can look like we'd doing stuff like a proper project :-)

**Comment by RedX2501** [comment]
You can try the milestone feature of github.

**Comment by RedX2501** [comment]
Closed in favour of the milestones.

**Comment by jakubgarfield** [comment]
Having milestones is a great idea! :+1:
