### ISSUE TITLE
Cleanup the routing table

### ISSUE THREAD

**Issue by RedX2501** [jakubgarfield/Bonobo-Git-Server#521]
For #520 I needed to add an entry to the routing table. I noticed that we have many out of date entries in there.

We definitely need to clean the table up.

The question is are there any advantages in doing the routing using MVC attributes since we are using version 5.0?

**Comment by willdean** [comment]
I like attribute-routing for stuff which is used in a small number of places (like the GitController for example).  I've only ever used them mixed with a 'traditional' routing table, so I don't really know whether it would be good to replace everything with them, but I'm :+1: on introducing them for new stuff.

A related useful (perhaps!) task would be to review where URLs are being hand-assembled rather than built with the route-aware helpers and replace that where possible with code which understands the routing.  (I know the Git URLs are done like this, and it isn't exactly a work of art...)

**Comment by KY4U** [comment]
Hello,

I believe my issue may be related to the routing table.  My installation is on an Azure webapp.  After pulling and publishing the latest code from 03/14/16 I'm getting 401 errors for urls that reference /info/refs?service=git-upload-pack

The problem is that the generated url contains only the webapp name and not the full url.  Here is an example:  https://mywebappname:80/git/my_repo.git/info/refs?service=git-upload-pack

If using the Azure domain then the url would be: https://mywebappname.azurewebsites.net:80/git/my_repo.git/info/refs?service=git-upload-pack

or if the actual Azure custom domain were used:
https://mycustomdomain.com/git/my_repo.git/info/refs?service=git-upload-pack

Please advise.
Thanks

**Comment by willdean** [comment]
Is this URL with the ?service= part on it coming out of a Git error message?   

Can you paste both the error message and the Git URL which is on the 'Repository Details' page within Bonobo?

**Comment by KY4U** [comment]
The incorrect url I'm getting from the error log directory in Azure.

HTTP Error 401.0 - Unauthorized
You do not have permission to view this directory or page.
Requested URL:  https://nccos-coastalscienceadmin-web:80/git/Powershell_MergeXML.git/info/refs?service=git-upload-pack

Repository URL: https://admin.coastalscience.noaa.gov/git/Azure-Powershell.git

Basically when I attempt to get to /Repository/Detail/asldkjalsdkfj I end up getting a Bonobo error page and I find this error in the log files.

Thanks for the help.

**Comment by willdean** [comment]
@KY4U Sorry, I am really struggling to get a grip on what's happening here.

Can you confirm how much of this is true:

1. You've cloned a repository from https://admin.coastalscience.noaa.gov/git/Azure-Powershell.git
2. Cloning and pulling is OK, but when you try to push, you get an error from the Git client
3. You can't provide the error message from the Git client, but it corresponds to the Azure error you posted above.

You've provided two different repository names - "Powershell_MergeXML.git" and "Azure-Powershell.git" - I'm not really clear how they might be related, and I'm not clear what the `asldkjalsdkfj` bit was meant to represent - was that a Guid?

We're going to need some really systematic stuff to try to get to the bottom of this - you'll have to work through cloning a repo and then pushing it and see which bits work and which don't.  

Something that might also be helpful is to go to the /home/diagnostics page on the Bonobo server, and then paste the results in here.

**Comment by KY4U** [comment]
Sorry, I made a typo in the last post.  I will try to clarify here.

Repository URL: https://admin.coastalscience.noaa.gov/git/Azure-Powershell.git

These errors occur when I am logged into the remote Git Server at https://admin.coastalscience.noaa.gov/git

When I attempt to get to the details page for the Azure-Powershell repo, I would click on this link:
https://admin.coastalscience.noaa.gov/git/Repository/Detail/fcb295a4-d285-4dea-b4a4-58ec93ce1e6b

The page will error out and I will find in the Azure logfile this:
HTTP Error 401.0 - Unauthorized
You do not have permission to view this directory or page.
Requested URL: https://nccos-coastalscienceadmin-web:80/git/Azure-Powershell.git/info/refs?service=git-upload-pack

The problem is that **nccos-coastalscienceadmin-web** is the name of the azure webapp, not the correct Azure url.  The correct Azure url would be nccos-coastalscienceadmin-web.azurewebsites.net

If the correct Azure url were generated, the Requested URL should be:
https://**nccos-coastalscienceadmin-web.azurewebsites.net**:80/git/Azure-Powershell.git/info/refs?service=git-upload-pack

An even better url would be the one that uses the custom domain for that webapp, which is admin.coastalscience.noaa.gov. That generated url should be:
https://nccos-coastalscienceadmin-web:80/git/Azure-Powershell.git/info/refs?service=git-upload-pack

I am seeing hundreds of these error pages in my log files all resulting from the incorrect url to the /info/refs?service=git-upload-pack pages.

I'm not having any trouble cloning, pulling, or pushing from by GUI.

Hope that information helps.
Kirk

**Comment by willdean** [comment]
The 401 error in Azure is not caused by clicking on that details link in a web browser.  The 401 error is coming from a Git client attempting a push.   Nothing within the web interface ever generates that sort of URL with the service=git-upload-pack stuff - it's built-up by a Git client.

I think there are two unrelated problems here:

1. You can't get to a repository details page without getting an error in Bonobo.  
2. A Git client somewhere is trying to push at a repository called Azure-Powershell.git and is getting refused permission.

I'd like to try and deal with '1' first - can you look in the app_data directory on the server for a file called Bonobo.Git.Server.Errors.log - if it's small, can you attach the file here, if it's huge can you just cut and paste the last part of the file?

**Comment by KY4U** [comment]
Thanks for the clarification.  I'll check my GUI to see if there is something going on there.

See attached file for error log.

[Uploading Bonobo.Git.Server.Erro
[partial_error_log.pdf](https://github.com/jakubgarfield/Bonobo-Git-Server/files/174617/partial_error_log.pdf)
rs.pdf…]()

**Comment by willdean** [comment]
@KY4U - Thanks for the log - it reveals a problem in the master code at the moment in this respect - PR #524 should get you through this for now, if you want to merge that branch into your own code.

**Comment by KY4U** [comment]
Will, thanks again for taking the time to work through this.  I certainly appreciate the help, and the fix.  I'll let you know if I still encounter these issues.

Regards,
Kirk
