### ISSUE TITLE
AD plugin not working for domain forest

### ISSUE THREAD

**Issue by mr-miles** [jakubgarfield/Bonobo-Git-Server#562]
Hi,

I have set up bonobo git server at my workplace and it is all looking good.  We have a weird AD setup with multiple domains, and I am finding that users from the non-default domain are not able to log in.  I think the problem is that they are not being created as a user in the backend.

I think I've traced this back to UpdateUsers.UpdateUsers.

The code gets the group and enumerates over the members.  However, for each member it then attempts to retrieve the principal from the default domain.  In my case this returns null because the user needs to be retrieved from the domain specified in their UserPrincipalName.

For example, if the members group is DOMAIN1\GitGroup and the problem user is DOMAIN2\ProblemUser, then Problemuser can only be retrieved from DOMAIN2.

Are you open to a pull request?

Thanks

Miles

**Comment by willdean** [comment]
Yes, we would definitely consider a pull-request.   We generally struggle to test/maintain the AD stuff at the moment, so good-quality AD work will probably be well-received.

If you're testing the 5.2 rather than with the code from the master branch, you should definitely work with the master code, because there have been huge changes since 5.x.  

I am not looking at the code right now, but ISTR there are already some places in the code where the domain is extracted from the UPN and used instead of the default domain - if you've found a place where this isn't happening, then perhaps you could try and find a consistent solution.

**Comment by larshg** [comment]
@mr-miles do you have multiple servers as well with different DNS names? And then a trust between these servers?

**Comment by larshg** [comment]
@mr-miles have you tried the recent releases?

**Comment by larshg** [comment]
Closing this due to no response. If the users from the second domain is added to the first domains usergroup - it should be possible that the users is found in the global catalogs. But I'm far from certain about this.
