### ISSUE TITLE
Enable password reset.

### ISSUE THREAD

**Issue by jakubgarfield** [jakubgarfield/Bonobo-Git-Server#59]

**Comment by KY4U** [comment]
Hello @kengibous 

I discovered an issue with password reset digests not being found in the cache.  It turns out that the digest value is added to the cache in its original state (unencoded).  That digest is then urlencoded utf8 and emailed to the requester.  When the user clicks on the return link, the digest value is improperly urlencoded.  This results in the digest value not being found in the cache and the user is unable to change their password.

In HomeController.cs, please change line 51 from:
digest = HttpUtility.UrlDecode(digest);

to

digest = HttpUtility.UrlDecode(digest,Encoding.UTF8);

Thanks!

**Comment by RedX2501** [comment]
@kengibous Any chance of turning that into a PR? Thank you.

**Comment by kengibous** [comment]
@RedX2501 @KY4U Thank you both pull request has been sent

**Comment by RedX2501** [comment]
Merged with 353ee206

**Comment by shnigganoo** [comment]
hi, I see this has been closed but it's still broken in the latest release.  Any chance this will be fixed soon.  I am running version 5.2.0.0 and have the same issue as commented by KY4U on Aug 7, 2015.

Thanks

**Comment by willdean** [comment]
I think you'll find it's fixed in 6.0 - you can get the latest pre-release version of that from the AppVeyor link on the front page (look in the AppVeyor Artifacts) .

Take a backup of you database before upgrading, because 6.0 does a big database mod.
