### ISSUE TITLE
Changing from Internal Membership to Active Directory loses repo settings

### ISSUE THREAD

**Issue by dniesen** [jakubgarfield/Bonobo-Git-Server#607]
A previous team installed Bonobo Git and we've taken it over and would prefer to use the Active Directory member service instead of the Internal.  We tried switching to ActiveDirectory but after the change all of the repo settings are lost.  Switching back to Internal member service brings the repo settings back with no problem.

Is there a supported way of switching between the two?

**Comment by willdean** [comment]
@dniesen Sadly, I don't think this is easy to do, because for reasons unknown to the current developers, when you're using AD, all the database info is stored in a separate home-brew json database, rather than in the Sqlite DB.

I think this is unfortunate for several reasons, yours being one of them.

I'm not aware of a straightforward way to transfer everything, either, thought it wouldn't be a very difficult bit of code to write.
