### ISSUE TITLE
Cannot show Chinese on diff of Committing

### ISSUE THREAD

**Issue by Elite-stay** [jakubgarfield/Bonobo-Git-Server#614]
Files use ANSI coding.

**Comment by willdean** [comment]
@Elite-stay Could you please attach a file which demonstrates this problem?

**Comment by RedX2501** [comment]
Well, ansi does not contain any character points that map to chinese. So you probably created the file using a chinese codepage in (lets assume) notepad.

Now Bonobo is probably running on a server which defaults to an US codepage. Since the plain text document has no encoding information it will try to open it as a plain text file and you will see garbled text.

You have two options:

1. Use UTF-8 (preferred)
2. Change the default encoding of the web-app. Can't help you here. You'll need to google.
