### ISSUE TITLE
Date format

### ISSUE THREAD

**Issue by holiiveira** [jakubgarfield/Bonobo-Git-Server#616]
Is it possible to change the date format that is shown without confirmation?

`MM/dd/yyyy HH:mm:ss to dd/MM/yyyy HH:mm:ss`

![commit_date](https://cloud.githubusercontent.com/assets/4368491/20599347/c17ae56e-b234-11e6-8d7a-f5472965bdbd.PNG)

![iis_format](https://cloud.githubusercontent.com/assets/4368491/20599343/bf1481ae-b234-11e6-8b0a-ee8a9b0b982f.PNG)

**Comment by willdean** [comment]
What is the date order in the pt-BR culture?

**Comment by mauricio-sonegatti** [comment]
In pt-BR culture the date order is dd/MM/yyyy HH:mm:ss

**Comment by willdean** [comment]
For some reason, in commit 04aa67ba8 a couple of date formattings were changed to use `CultureInfo.InstalledUICulture`, which I don't think is correct (presumably it made some problem that someone at the time was having go away, but only really by luck).

Assuming you can't change the default locale for your whole server, then this will need to be fixed in Bonobo.

If you're in a position to try this, then edit `_commits.cshtml` and remove the reference to  `CultureInfo.InstalledUICulture` from line 15 (just leave the plain `ToString()`).

I wasn't involved with the project at the time, and I don't know the history of this change.

**Comment by holiiveira** [comment]
Thanks for the feedback.
I made a change, including some entries for the pt-BR translation.

Regards
