### ISSUE TITLE
git webpage first loading slow

### ISSUE THREAD

**Issue by snz2** [jakubgarfield/Bonobo-Git-Server#638]
I have question.
why webpage first loading slow? first loading is  5second time
second loading is normal time. 

my bonobo git system is IIS on windows server
cpu is multi core and ram is best
bonobo git version is 5.2

regards

**Comment by latop2604** [comment]
You should try to enable iis preloadmode and set application pool start mode to AlwaysRunning.
See 
 > https://blogs.msdn.microsoft.com/vijaysk/2012/10/11/iis-8-whats-new-website-settings/
 > https://blogs.msdn.microsoft.com/vijaysk/2012/10/09/iis-8-whats-new-application-pool-settings/

One of the startup operations is to synchronize repository list. It scan the repos directory to find new ones to add to the database.

**Comment by snz2** [comment]
thanks reply.

I'm Already setting is on.
but still same slow.
normally, repositry sync is asyc with web page load?
why not web page load first?

**Comment by willdean** [comment]
Slow first-page load on ASP.NET applications is common, which is why there are various 'warming-up' options available in IIS.

Some versions of Bonobo are also very busy on the database, and you may find that 6.0 is much more efficient that 5.2 in this regard.

I'm going to close this because I don't think there's a general perf problem and I don't think anyone is going to work on a "5s to first page load after a cold start" problem.
