### ISSUE TITLE
Unblocking 6.0

### ISSUE THREAD

**Issue by willdean** [jakubgarfield/Bonobo-Git-Server#640]
There's already been some discussion about when 6.0's coming out - we're really stalled at the moment for the ability to actually get consistent test/feedback on the AD stuff - @larshg is, I think, the only active developer who has a real AD setup - obviously that lets him test on that, but doesn't help with any problems that other people might have.

My suggestion is that we merge whatever comes from #637 and then release something as '6.0-beta', and see if we can get some better feedback.  I'll do my best to respond quickly to people who report AD issues and see if we can work through those with them while we still have their attention.  

Past objections that people might be turned away by something which isn't perfect are valid (e.g. in #587), but I think are now outweighed by the risk that people are turned away because the project looks dead.  All wry jokes about companies who test their software on their customers aside, this is the reality of where we are.

@jakubgarfield I am happy to deal with making this release if you'd like to pass that work on - I guess I'd need access to the website project and also some details about the hosting/posting that's involved. 

@RedX2501 would be an obvious person to comment too...

**Comment by jakubgarfield** [comment]
I reckon you guys go ahead with 6.0 and just deploy it and see how it goes.

I'll try to write up and add access to the bonobogitserver.com and demo.bonobogitserver.com by the end of the week.

**Comment by rfmsimoes** [comment]
hello everyone,

I'm new using this git server.
It seems something light and powerful.

However I would like to know your opinion about some topics:

1 - Why user (without admin rights) when look into the list os users belong to a team and press the "back button" is redirect into the list of all team (Teams/Index) intead to be redirect to the previous page?

If tou try to redirect someone to the lnedx of Team without the admin right a error about permission will show...I think it will be better to use something like: href="@Request.UrlReferrer" instead of   href="@Url.Action("Index")

2 - In repository details instead showing part of the URL (when I was exploring the server I noticed that) like http://localhost(....) why not show the machine name?

In SetGitUrls function in Repository Contrroller instead using the Request.Url.Host why not using something like System.Net.Dns.GetHostName() ?

Because I can access a server by name or by IP...but if I try to send the link to someone the PC name will be more easy and the advantage of this approach is even I connected directly in the machine by remote desktop I can copy past the url in repository detail without care about the localhost part.

3 - Why a user (even without admin rights) can change their username? shouldn't it be readonly?
shouldn't be only admin or users with admin rights be able to do that?


I know this is nothing very important and with a low impact in everything.
But I just would like to know your opinion. ( I've done this changes at my side =D )

And by the way, what do you think about the possibility to be able to add more roles than administrator? I know this could have a hudge impact in all website...but just one idea. :)

**Comment by willdean** [comment]
@rfmsimoes - Thanks for the feedback, but it's in the wrong place - please don't file issues as comments on an unrelated issue.

Instead, create new issues, one for each bug / comment, and we'll look at them separately.

This might be interesting / useful https://guides.github.com/features/issues/

**Comment by jakubgarfield** [comment]
@willdean I added [New Release](https://github.com/jakubgarfield/Bonobo-Git-Server/blob/master/Bonobo.Git.Server/Properties/AssemblyInfo.cs) section to the projects README and also updated the website [readme](https://github.com/jakubgarfield/Bonobo-Git-Server) and added you as a contributor. Let me know if there is something missing.

Next step is to investigate how to share access to the [demo](demo.bonobogitserver.com) server if it is possible (it should be).

**Comment by jakubgarfield** [comment]
Cool, I set up continuous deployments to demo.bonobogitserver.com from master branch – so one thing we don't have to worry about – unless someone changes admin password :/.

**Comment by willdean** [comment]
Done, it's up.  Let the shouting begin...
