### ISSUE TITLE
some files not uploaded to repository

### ISSUE THREAD

**Issue by sadeghrz** [jakubgarfield/Bonobo-Git-Server#699]
hi,
some files and folders like bin folder or ApplicationInsights.config file not uploaded to remote repository.
any filter have?

**Comment by willdean** [comment]
There isn't any filtering like this in Bonobo.

**Comment by sadeghrz** [comment]
but i have an asp.net mvc app , i push it to bonobo from visual studio team explorer , bin folder and some other files not pushed, can i add files directly to repository?

**Comment by willdean** [comment]
@sadeghrz That sounds like something the Visual Studio Team Explorer Git client is doing - you can use any Git client with Bonobo, and you may find another one which suits you better.  You need to check if VS has created a .gitignore file which is excluding the things you want, because that will affect every client.

I'm going to close this because I don't think it's a Bonobo problem, and there are better places to get Git support than here (Stackoverflow has every possible Git question already answered.)
