### ISSUE TITLE
Truncate history commits

### ISSUE THREAD

**Issue by hxmcn** [jakubgarfield/Bonobo-Git-Server#866]
Is there a function that can truncate history commits?
When I use Bonobo for years, some Repositories are inflated to giga-bytes because of some big media files are committed.
I want to truncate too old commits to streamline Repository to save disk space and increase clone speed, anyone have ideals? 
Thanks in advance!

**Comment by willdean** [comment]
The repositories are just Git repositories (Bonobo contains a copy of Git), so if you're able to run ordinary programs on the machine which hosts your server, then you can use whatever process anyone would use to truncate history.

This might be a good starting point:  https://passingcuriosity.com/2017/truncating-git-history/

I'm going to close this, because I think it's a sufficiently rare operation that I don't think it's easy enough to do outside Bonobo
