### ISSUE TITLE
Improvements for AD Integration

### ISSUE THREAD

**Issue by rozniak** [jakubgarfield/Bonobo-Git-Server#870]
Hi guys,

I don't know how actively this project is maintained nowadays, but I have been looking into some bits surrounding AD integration lately as I was having some issues with it.

I have done some work on improving the performance of the AD backend via caching of Principal objects and whatnot. Previously whenever I issued `git push` or `git pull` (anything involving the remote) it would take roughly 15 seconds to complete. After my caching work it takes less than a second.

I have the work pushed to my fork here: https://github.com/rozniak/Bonobo-Git-Server/commits/dev-adfix

I haven't contributed much to other repos here on GitHub but I would be happy to do any work required to merge in these changes assuming they considered 'worthy' by you guys. :stuck_out_tongue: 

I might do some other bits on top of this (#864 sounds good to me), I just mostly wondered if pull requests are being actively accepted right now and whether you consider my work worth merging.

Cheers!

**Comment by willdean** [comment]
Thanks for the input.  I am the last surviving maintainer and am almost completely negligent, other than security stuff.  The AD integration is particularly difficult for me because it's very hard to test without running AD, and it's had to set up AD just for testing without causing other problems on the network.

There were some (IMO) rather poor quality drive-by changes made to the AD support before I was involved, by people who didn't stay around to defend their input, so it would be great to have someone who wanted to work on AD.   

If you would like to make a commit into a PR, then I'd definitely consider merging it.   There are guidelines for contributing to OSS all over the place, but the main things that make *me* want to consider a PR are:

* Ideally you would open an issue which described the problem, then a PR which fixed the problem and referred to the issue.
* Try to stick to the project's existing style, even if that's not your personal preference / or your Resharper defaults
* Don't mix unrelated trivial cleanup (whitespace changes, etc) with the actually changes which are relevant to the PR
* If possible, fix one thing per issue + PR

Obviously, simple PRs with a very small number of commits in them are much easier to review than very complex ones, particularly where multiple commits overwrite each other which means you have to review them backwards.

I basically learned everything (!) that I know about Git by helping on OSS on GitHub, so I would be happy to help you put things into a form I was happy with.  You just have to be prepared for nit-picking.  (Go and contribute to  .NET Core if you find you *really* like nit-picking...)

**Comment by rozniak** [comment]
No problem - nit-picking is fine by me, always happy to get feedback. :grin: 

So a couple things then:
- Would you like me to open separate issues for the changes I mentioned in the OP and close this one?
- The caching stuff is done in 3 commits, I can shift those over to another branch - would you want them cherry picked or squashed?

**Comment by willdean** [comment]
"Would you like me to open separate issues for the changes I mentioned in the OP and close this one?"

Yes, please - don't make it into a huge admin task, but if there's some clear explanation of why something came about that does help

"The caching stuff is done in 3 commits, I can shift those over to another branch - would you want them cherry picked or squashed?"

I don't think it matters much, though you have clearly lulled me into giving a false impression of expertise and are now cleverly revealing that you're far more on top of this stuff than I am.  As long as there's one commit (or a simple series of them which don't overlap too much) based on top of the current head, than there shouldn't be any problem reviewing it or merging it.  GH can squash multiple commits as it merges anyway - so we don't need to be excessive about that, it's just where people make howling mistakes in one commit and then correct it in a later one, it's nicer just to not see them at all.

**Comment by rozniak** [comment]
> Yes, please - don't make it into a huge admin task, but if there's some clear explanation of why something came about that does help

Should only be two things for now, I'll keep 'em brief. :stuck_out_tongue: 

> I don't think it matters much, though you have clearly lulled me into giving a false impression of expertise and are now cleverly revealing that you're far more on top of this stuff than I am. [...]

I know my way around Git itself (at least enough to hopefully not screw it up)... trouble is I have rarely made contributions as a team so figured I'd ask for advice because I might have a stupid workflow from working on my own. :dizzy_face: 

I'll sort out some bits and then send over the relevant issues+PRs - I'll close this particular issue. :+1: 

Thanks!
